<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="main-footer">
        <div class="link3">
            <h3>FIQUE POR DENTRO</h3>
            <ul>
                <li><a>Assine a nossa Newletter para não perder nenhuma das promoções !</a></li>
            </ul>
            <div class="icons">
                <a href="https://pt-br.facebook.com" target="_blank"><img src="{{media url="wysiwyg/facebook.png"}}" alt="Icone do Facebook" width="37" height="37"> &nbsp;</a><a href="https://www.instagram.com/" target="_blank"><img src="{{media url="wysiwyg/instagram.png"}}" alt="Icone do Instagram" width="38" height="38"> &nbsp;</a><a href="https://www.youtube.com/" target="_blank"><img src="{{media url="wysiwyg/youtube.png"}}" alt="Icone do YouTube" width="44" height="31"> &nbsp;</a><a href="https://br.pinterest.com/" target="_blank"><img src="{{media url="wysiwyg/pinterest.png"}}" alt="Icone do Pinterest" width="41" height="41"> &nbsp;</a>
            </div>
        </div>
    </div>
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
